- aws:
    region: ap-southeast-1
    account-id: 908177370303
  location: ./compiler/templates/aws-artifact-storage.yaml
  template:
    name: smlf-dataengineering-cfn-artifact-bucket
    parameters:
      artifact-bucket: 'smlf-dataengineering-deployer-artifact-bucket'
      deployment-registry-table-name: 'smlf-dataengineering-deployer-deployment-registry'
  lambdas: []

- aws:
    region: ap-southeast-1
    account-id: 908177370303
  location: ./compiler/templates/aws-cfn-deployer.yaml
  template:
    name: smlf-dataengineering-cfn-deployer
    parameters:
      stack-prefix: 'smlf-dataengineering-cfn'
      deployment-registry-table-name: 'smlf-dataengineering-deployer-deployment-registry'
      artifact-bucket: 'smlf-dataengineering-deployer-artifact-bucket'
      state-machine-name: 'smlf-dataengineering-cfn-deployer'
    artifact-bucket: 'smlf-dataengineering-deployer-artifact-bucket'
    stack-prefix: 'smlf-dataengineering-cfn'
    deployment-registry-table-name: 'smlf-dataengineering-deployer-deployment-registry'
    lambda-code-key: 'packages/smlf-dataengineering-cfn-deployer/lambdas/'
  lambdas:
    - name: package
      location: ./compiler/deployer/
      template-attribute: lambda-code-key
      bucket: smlf-dataengineering-deployer-artifact-bucket

- aws:
    region: ap-southeast-1
    account-id: 908177370303
  location: ./compiler/templates/aws-ci.yaml
  template:
    name: smlf-dataengineering-cfn-deployer-ci
    parameters:
      template-deployer-repository-name: smlf-dataengineering-template-deployer
      deployer-codebuild-name: smlf-dataengineering-template-deployer-build
      deployer-artifact-bucket: smlf-dataengineering-deployer-artifact-bucket
      deployer-state-arn: arn:aws:states:ap-southeast-1:908177370303:stateMachine:smlf-dataengineering-cfn-deployer
  lambdas: []

- aws:
    region: ap-southeast-1
    account-id: 908177370303
  location: ./compiler/templates/aws-deployer-service.yaml
  template:
    name: smlf-dataengineering-cfn-deployer-service
    parameters:
      deployer-codebuild-service-name: smlf-dataengineering-template-deployer-service
      deployer-artifact-bucket: smlf-dataengineering-deployer-artifact-bucket
      deployer-state-arn: arn:aws:states:ap-southeast-1:908177370303:stateMachine:smlf-dataengineering-cfn-deployer
      deployer-trigger-lambda-name: smlf-dataengineering-deployer-trigger-service
    lambda-code-key: 'packages/smlf-dataengineering-cfn-deployer/lambdas/'
  lambdas:
    - name: service
      location: ./compiler/service/
      template-attribute: lambda-code-key
      bucket: smlf-dataengineering-deployer-artifact-bucket

# - aws:
#     region: ap-southeast-1
#     account-id: 908177370303
#   location: ./compiler/templates/aws-notification.yaml
#   template:
#     name: smlf-dataengineering-cfn-deployer-notif-de
#     parameters:
#       topic-name: de
#       stack-prefix: 'smlf-dataengineering-cfn'
#     subscriptions:
#       - matthieu.blais1@gmail.com
#   lambdas: []
