AWSTemplateFormatVersion: '2010-09-09'
Description: A step function to deploy CFN templates

Parameters:

  TemplateDeployerRepositoryName:
    Type: String

  DeployerCodebuildName:
    Type: String

  DeployerArtifactBucket:
    Type: String

Resources:

  TemplateDeployerRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref TemplateDeployerRepositoryName
      RepositoryDescription: "CI for cfn deployment"

  CloudWatchEventTriggerRule:
    Type: 'AWS::Events::Rule'
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
            - !GetAtt [TemplateDeployerRepository, Arn] 
        detail:
          event:
          - referenceCreated
          - referenceUpdated
          referenceType:
          - branch
          referenceName:
          - master
          - staging
          - dev
      Targets:
      - Arn: !GetAtt [DeployerCodeBuild, Arn]
        RoleArn: !GetAtt [CloudWatchEventTriggerRole, Arn]
        Id: codebuild-pipeline

  CloudWatchEventTriggerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: cfn-deployer-cloudwatch-event-trigger-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'codebuild:StartBuild'
                Resource: 
                  - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${DeployerCodebuildName}'

  DeployerCodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Ref DeployerCodebuildName
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Deploy facts
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/standard:4.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: ARTIFACTS_BUCKET
          Type: PLAINTEXT
          Value: !Ref DeployerArtifactBucket
      ServiceRole: !Ref CodebuildServiceRoleArn
      Source:
        Location: !Sub "https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${TemplateDeployerRepositoryName}"
        Type: CODECOMMIT
        GitCloneDepth: 1
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - aws s3 cp . s3://$ARTIFACTS_BUCKET/deployer/ --recursive --exclude "*" --include "*.yaml" --include "*.py"

  CodebuildServiceRoleArn:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: cfn-deployer-codebuild-ci-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${DeployerCodebuildName}:*'
              - Effect: Allow
                Action:
                  - 'codecommit:GitPull'
                Resource:
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${TemplateDeployerRepositoryName}'
              - Effect: Allow
                Action:
                  - 's3:List*'
                Resource:
                  - !Sub 'arn:aws:s3:::${DeployerArtifactBucket}'
              - Effect: Allow
                Action:
                  - s3:Put*
                  - s3:Get*
                  - s3:HeadObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DeployerArtifactBucket}/*'