AWSTemplateFormatVersion: '2010-09-09'
Description: A step function to deploy CFN templates
Resources:

  DeploymentFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: {{ StackPrefix }}-deployer-notification
      TopicName: {{ StackPrefix }}-deployer-notification
      {% if Subscribers is defined %}
      Subscription:
      {% for subscriber in Subscribers %}
        - Endpoint: {{ subscriber }}
          Protocol: email
      {% endfor %}
      {% endif %}

  DeployTemplates:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: {{ ArtifactBucket }}
        S3Key: {{ LambdaCodeKey }}
      Description: "Deploy CFN template"
      FunctionName: {{ StackPrefix }}-deployer-deploy-template
      Handler: "deployer.deploy_template"
      MemorySize: 128 
      Role: !GetAtt [LambdaDeployerRole, Arn]
      Runtime: python3.8
      Timeout: 15
      {% if AwsDeploymentRole is defined %}
      Environment:
        Variables:
          ASSUME_ROLE_ARN: {{ AwsDeploymentRole }}
      {% endif %}

  StatusTemplates:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: {{ ArtifactBucket }}
        S3Key: {{ LambdaCodeKey }}
      Description: "Get status of CFN template"
      FunctionName: {{ StackPrefix }}-deployer-get-status
      Handler: "deployer.status_template"
      MemorySize: 128 
      Role: !GetAtt [LambdaDeployerRole, Arn]
      Runtime: python3.8
      Timeout: 15
      {% if AwsDeploymentRole is defined %}
      Environment:
        Variables:
          ASSUME_ROLE_ARN: {{ AwsDeploymentRole }}
      {% endif %}

  TemplateDeployer:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: {{ StateMachineName }}
      DefinitionString: |-
        {
          "StartAt": "Deploy template",
          "States": {
            "Deploy template": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:{{ AwsRegion }}:{{ AwsAccountId }}:function:{{ StackPrefix }}-deployer-deploy-template",
              "Next": "Wait 10s"
            },
            "Wait 10s": {
              "Type": "Wait",
              "Seconds": 10,
              "Next": "Status"
            },
            "Status": {
              "Type": "Task",
              "Resource": "arn:aws:lambda:{{ AwsRegion }}:{{ AwsAccountId }}:function:{{ StackPrefix }}-deployer-get-status",
              "Next": "Is deployed?"
            },
            "Is deployed?": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.Status",
                  "StringEquals": "SUCCESS",
                  "Next": "Success"
                },
                {
                  "Variable": "$.Status",
                  "StringEquals": "FAIL",
                  "Next": "Notify Admins"
                }
              ],
              "Default": "Wait 10s"
            },
            "Notify Admins": {
              "Type": "Task",
              "Resource": "arn:aws:states:::sns:publish",
              "Parameters": {
                "TopicArn": "arn:aws:sns:{{ AwsRegion }}:{{ AwsAccountId }}:{{ StackPrefix }}-deployer-notification",
                "Message.$": "$.ErrorMessage"
              },
              "Next": "Fail"
            },
            "Success": {
              "Type": "Succeed"
            },
            "Fail": {
              "Type": "Fail",
              "Cause": "$.ErrorMessage"
            }
          }
        }
      RoleArn: !GetAtt [StateMachineRole, Arn]

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: StateMachinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:{{ StackPrefix }}-deployer-*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - arn:aws:sns:*:*:{{ StackPrefix }}-deployer-notification
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:Describe*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:PutMetricFilter
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - cloudwatch:PutMetricAlarm
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - events:PutTargets
                  - events:PutRule
                  - events:DescribeRule
                Resource:
                  - !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForStepFunctionsExecutionRule"

  LambdaDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: StateMachinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              {% if AwsDeploymentRole is defined %}
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - {{ AwsDeploymentRole }}
              {% endif %}
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetBucketAcl
                Resource:
                  - arn:aws:s3:::{{ ArtifactBucket }}
              - Effect: Allow
                Action:
                  - s3:HeadObject
                  - s3:GetObjectTagging
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetObjectTagging
                Resource:
                  - arn:aws:s3:::{{ ArtifactBucket }}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:SetStackPolicy'
                  - 'cloudformation:ValidateTemplate'
                  - 'iam:PassRole'
                Resource: '*'