AWSTemplateFormatVersion: '2010-09-09'
Description: A step function to deploy CFN templates
Resources:

  ArtifactStoreBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: {{ ArtifactBucket }}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionExpirationInDays: 3
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled
