AWSTemplateFormatVersion: '2010-09-09'
Description: A step function to deploy CFN templates

Parameters:

  DeployerCodebuildServiceName:
    Type: String

  DeployerTriggerLambdaName:
    Type: String

  DeployerArtifactBucket:
    Type: String

  DeployerStateArn:
    Type: String

Resources:

  BuildTriggerLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref DeployerArtifactBucket
        S3Key: {{ LambdaCodeKey }}
      Description: "Trigger Codebuild job"
      FunctionName: !Ref DeployerTriggerLambdaName
      Handler: "trigger.handler"
      MemorySize: 128 
      Role: !GetAtt [LambdaServiceRoleArn, Arn]
      Runtime: python3.8
      Timeout: 15

  DeployerCodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Ref DeployerCodebuildServiceName
      Artifacts:
        Type: NO_ARTIFACTS
      Description: Service to deploy cfn stacks
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/standard:4.0"
        Type: LINUX_CONTAINER
        EnvironmentVariables:
        - Name: ARTIFACTS_BUCKET
          Type: PLAINTEXT
          Value: !Ref DeployerArtifactBucket
        - Name: DEPLOYER_STATE_MACHINE_ARN
          Type: PLAINTEXT
          Value: !Ref DeployerStateArn
      ServiceRole: !Ref CodebuildServiceRoleArn
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.8
              commands:
                - pip3 install boto3 Jinja2
            pre_build:
              commands:
                - aws s3 cp s3://$ARTIFACTS_BUCKET/deployer/service/main.py .
            build:
              commands:
                - [ -f ./bin/package.sh ] || /bin/bash ./bin/package.sh
                - python3 main.py
                
  CodebuildServiceRoleArn:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: cfn-deployer-codebuild-service-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${DeployerCodebuildServiceName}:*'
              - Effect: Allow
                Action:
                  - 's3:List*'
                Resource:
                  - !Sub 'arn:aws:s3:::${DeployerArtifactBucket}'
              - Effect: Allow
                Action:
                  - s3:Put*
                  - s3:Get*
                  - s3:HeadObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DeployerArtifactBucket}/*'
              - Effect: Allow
                Action:
                  - states:ListStateMachines
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - states:DescribeExecution
                  - states:DescribeStateMachineForExecution
                  - states:GetExecutionHistory
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - states:ListExecutions
                  - states:DescribeStateMachine
                  - states:StartExecution
                  - states:StopExecution
                Resource:
                  - !Ref DeployerStateArn

  LambdaServiceRoleArn:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: cfn-deployer-lambda-service-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - "*"
              - Effect: Allow
                Action: 'codebuild:StartBuild'
                Resource: 
                  - !GetAtt [DeployerCodeBuild, Arn]
            