AWSTemplateFormatVersion: '2010-09-09'
Description: A step function to deploy CFN templates

Parameters:

  TopicName:
    Type: String

  StackPrefix:
    Type: String

Resources:

  DeploymentFailureNotification:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${StackPrefix}-deployer-${TopicName}"
      TopicName: !Sub "${StackPrefix}-deployer-${TopicName}"
      {% if Subscriptions is defined %}
      Subscription:
        {% for subscription in Subscriptions %}
        - Endpoint: {{ subscription }}
          Protocol: email
        {% endfor %}
      {% endif %}


Outputs:

    DeploymentFailureNotification:
        Value: !Ref DeploymentFailureNotification
