AWSTemplateFormatVersion: '2010-09-09'
Description: Deployer storage layer

Parameters:

  ArtificatBucketName:
    Type: String

  DeploymentRegistryTableName:
    Type: String

Resources:

  ArtifactStoreBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref ArtificatBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - NoncurrentVersionExpirationInDays: 3
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled


  DeploymentRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "TemplateName"
          AttributeType: "S"
        - AttributeName: "DeploymentTimestamp"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "TemplateName"
          KeyType: "HASH"
        - AttributeName: "DeploymentTimestamp"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TableName: !Ref DeploymentRegistryTableName

Output:

  ArtificatBucketName:
    Value: !Ref ArtificatBucketName

  DeploymentRegistryTable:
    Value: !Ref DeploymentRegistryTable
