- aws:
    region: ap-southeast-1
    account-id: "908177370303"
  location: ./examples/template.yaml
  action: delete_stack
  template:
    name: deployer-example
    parameters:
      project-name: sdsfsdfsf
  lambdas: []
