project:
    name: taskcat
    regions:
    - <YOUR_REGION>
    s3_bucket: <YOUR_ARTIFACT_BUCKET>
  tests:
    default:
      template: ./templates.yaml
      regions:
      - ap-southeast-1
      parameters:
        ProjectName: demoapp
